kingdee/kdesign

site/src/static/style/index.less
=> fix:[cli] 首页IE11的兼容性问题修改

components/anchor/style/index.less, components/link/demo/basic.md, components/link/demo/color.md, components/link/demo/icon.md, components/link/demo/size.md, components/link/demo/underscore.md, components/spin/demo/children.md
=> fix: [anchor] 修复锚点鼠标悬浮上去的样式

components/split-panel/index.md, components/split-panel/style/index.less, components/split-panel/style/token.less
=> fix: [split-panel] 更新分隔容器视觉稿

components/message/content.tsx, components/message/index.md, components/message/style/index.less, components/message/style/token.less, components/select/index.md, components/select/style/token.less, components/tree/index.md, components/tree/style/index.less, components/tree/style/token.less
=> fix: [message] 修复组件视觉样式

components/base-data/base-data.tsx, components/base-data/index.md, components/base-data/style/index.less, components/base-data/style/token.less, components/menu/__tests__/__snapshots__/index.test.tsx.snap
=> fix: [base-data] 更正开放token属性及选中项颜色值

components/menu/demo/basic.md, components/menu/demo/basic_submenu.md, components/menu/demo/basic_thridmenu.md, components/menu/demo/collapsed.md, components/menu/demo/inline.md, components/menu/demo/inline_selected.md, components/menu/demo/theme.md, components/menu/demo/vertial_click.md, components/menu/index.md, components/menu/menu.tsx, components/menu/style/index.less, components/menu/style/mixin.less, components/menu/style/token.less, components/menu/subMenu.tsx, scripts/generate-token.js
=> Revert "fix: [menu]"

components/date-picker/style/index.less, components/date-picker/style/token.less, components/menu/__tests__/__snapshots__/index.test.tsx.snap, components/select/index.md, components/select/style/token.less
=> fix: [date-picker] 修复日期区间选择的选择块不跟随主题色的问题

components/_utils/usePopper.tsx, components/anchor/anchor.tsx, components/anchor/index.md, components/anchor/style/index.less, components/anchor/style/token.less, components/button/button.tsx, components/button/demo/group.md, components/button/group.tsx, components/button/index.md, components/button/index.tsx, components/button/style/index.less, components/button/style/token.less, components/carousel/carousel.tsx, components/config-provider/compDefaultProps.tsx
button: 
新增集合按钮
anchor：
修复视觉走查问题点
解决锚点组件锁住后重新打开，锚点浮层不能自动关闭问题
=> button，anchor

components/table/demo/b170_rangeSelection.md, components/table/feature/useRangeSelection.ts, components/table/index.md, components/table/interface.tsx, components/table/table.tsx
需更新包：   `"@kdcloudjs/table": "1.0.2"`
更新点：
- docs: [table] 完善primaryKey和行选中的说明
- feat: [table] 增加外部可配置表格复选框和单选框参数
- docs: [table] 更新表格api说明
- feat: [table] 增加范围选中功能
=> feat: table功能完善，可配置表格复选框和单选框参数，增加范围选中功能

components/checkbox/checkbox.tsx, components/menu/__tests__/__snapshots__/index.test.tsx.snap, components/radio/radio.tsx, components/transfer/__tests__/__snapshots__/index.test.tsx.snap
=> fix: [checkbox] 修复外层包裹添加点击事件,执行操作时触发两次的bug

docs/guide/customtopic.md
=> fix: [docs] 更正cra跳转链接

components/anchor/index.md, components/carousel/carousel.tsx, components/config-provider/compDefaultProps.tsx, components/dropdown/index.md, components/dropdown/style/index.less, components/dropdown/style/token.less, components/radio/radio.tsx, components/tree/demo/draggable.md, components/tree/demo/filter.md, components/tree/index.md, components/tree/style/index.less, components/tree/style/token.less, components/tree/tree.tsx, components/tree/treeHooks.tsx, components/tree/treeNode.tsx, components/tree/utils/treeUtils.tsx
修复单选defaultChecked不生效问题
新增节点过滤功能
锚点组件api文档调整
=> fix：radio，tree，anchor

components/_utils/usePopper.tsx
This reverts commit f487389d95ca759658b5bf7ff988de30aa485f9c.
=> Revert "fix: [Tooltip] 修复当触发元素在右上角，trigger=top时，浮层超出显示边界的问题"

components/checkbox/checkbox.tsx, components/tabs/demo/dynamic.md, components/tabs/index.md, components/tabs/style/index.less, components/tabs/style/mixin.less, components/tabs/style/token.less, components/tree/index.md, components/tree/style/index.less, components/tree/style/token.less, components/tree/treeNode.tsx
tree,tabs视觉走查
tree 异步加载loading显示不全问题
=> fix: tree,tabs

components/table/interface.tsx, components/table/table.tsx
开发者可以通过设置`Table`的`ref`的方式获得表格的api
=> feat: [table] 添加表格向外提供的api

components/config-provider/compDefaultProps.tsx, components/search/index.md, components/search/style/index.less, components/search/style/token.less, components/select/__tests__/__snapshots__/index.test.tsx.snap, components/select/__tests__/index.test.tsx, components/select/demo/multiple.md, components/select/demo/search.md, components/select/index.md, components/select/interface.tsx, components/select/option.tsx, components/select/select.tsx, components/select/style/index.less, components/select/style/mixin.less, components/select/style/token.less, components/split-panel/style/index.less
search: 增加搜索框圆角
select: 新增支持直接在输入框内输入内容搜索
=> fix: search,select

components/table/demo/a10_select.md, components/table/index.md, components/table/interface.tsx, components/table/table.tsx
=> feat: [table] 行选中增加高亮已选行属性及说明

components/_utils/usePopper.tsx, components/tooltip/demo/controll.md, components/tooltip/demo/function.md, components/tooltip/demo/trigger.md, components/tooltip/demo/visiable.md
=> fix: [tooltip] trigger添加mouseleave事件控制显隐

components/table/demo/a70_columnGroup.md, components/table/feature/colGroupExtendable.ts, components/table/interface.tsx, components/table/table.tsx
表格添加分组列展开收缩特性
表格版本:@kdcloudjs/table 1.1.5-canary.1
=> feat: [table] 添加表格分组列展开收缩特性

components/dropdown/__tests__/__snapshots__/index.test.tsx.snap, components/dropdown/__tests__/index.test.tsx, components/dropdown/dropdown.tsx, components/dropdown/menu.tsx
当menu的item只有一项时不触发onClick事件 以及 menu 上的class 没有被继承的问题
=> [dropdown]: 当menu的item只有一项时不触发onClick事件 #262

CONTRIBUTING.md
docs:[CONTRIBUTING] 贡献文档教程 git添加远程仓库命令错误 fixes: kdcloudone#354
=> docs:[CONTRIBUTING] 贡献文档教程 git添加远程仓库命令错误 fixes: kdcloudone#354

components/slider/demo/stepper.md
doc: [slider] 滑动器 结合 步进器使用，步进器 范围不受控 fixes: kdcloudone#367
=> doc: [slider] 滑动器 结合 步进器使用，步进器 范围不受控 fixes: kdcloudone#367

components/tree-select/style/index.less
[bug] [tree-select] 树选择器 大数据样例 存在双滚动条 fixes: #380
=> [bug] [tree-select] 树选择器 大数据样例 存在双滚动条 #380

site/src/template/layout/header/msearch.less
=> fix: [cli] 修复 MDocsSearch 搜索结果显示异常的问题 fixed kdcloudone#378

site/src/template/layout/header/docs-search.tsx, site/src/template/layout/header/index.tsx
本地启动项目，docs-search 匹配结果url主站为 react.kingdee.design,不是localhost fixes: kdcloudone#359
=> 本地启动项目，docs-search 匹配结果url主站为 react.kingdee.design,不是localhost fixes:kdcloudone#359

site/bisheng.config.js
[bug]解决项目在在线沙盒CodeSandBox中无法演示，提示 Invalid Host header的问题 fixes: kdcloudone#374
=> [bug]解决项目在在线沙盒CodeSandBox中无法演示，提示 Invalid Host header的问题 fixes: kdcloudone#374

components/cascader/cascader.tsx
This reverts commit a1cdb684387b685d8182a7f732c7cc0c3c22c00d.
=> Revert "fix: [cascader]修复maxTagPlaceholder重复执行问题 fix #404"

components/locale/zh-CN.tsx, components/table/table.tsx
需更新@kdcloudjs/table 1.2.0-canary.6
=> feat: [table] 新增国际化配置

components/table/index.md
@albyben 需升级 [table1.2.0-canary.8](https://www.npmjs.com/package/@kdcloudjs/table/v/1.2.0-canary.8)
=> docs: [table] 增加列flex属性说明

components/table/demo/b171_rowDrag.md, components/table/feature/useRowDrag.ts, components/table/index.md, components/table/interface.tsx, components/table/table.tsx
提交需要合并到稳态分支，table版本更新到1.2.0-canary.10
=> feat:[table] 表格增加行拖拽功能

components/table/table.tsx
=> fix: [table] 修复表格默认加载输出异常警告日志

components/color-picker/color-picker-panel.tsx, components/color-picker/color-picker.tsx, components/color-picker/utils/colorFormat.ts, package.json, typings/custom-typings.d.ts
This reverts commit ef2a6aa4c9c64daabc43f1c2ad63108b8faf3931.
=> Revert "fix: [color-picker] 修复由于第三包不支持ie11的问题 fix #739"

components/table/api.tsx
=> feat: 表格适配 RTL, 表格焦点问题
